cifar100:
  train_path: /data_library/cifar100/train
  test_path: /data_library/cifar100/test
  subfolder: true 
  num_classes: 21
  crop:
    size: [32, 32]
    padding: 4
  random_horizontal_flip: true
  mean:
    cifar100: [0.5071, 0.4865, 0.4409]
    two_class: [0.5071, 0.4866, 0.4409]
    aquatic_mammals: [0.4242, 0.4783, 0.4975]
    fish: [0.4162, 0.4626, 0.4577]
    flowers: [0.5233, 0.4080, 0.3058]
    food_containers: [0.5824, 0.5459, 0.5111]
    fruit_and_vegetables: [0.6010, 0.4927, 0.3616]
    household_electrical_devices: [0.5573, 0.5368, 0.5251]
    household_furniture: [0.6104, 0.5407, 0.4902]
    insects: [0.5568, 0.5380, 0.4312]
    large_carnivores: [0.4719, 0.4395, 0.3713]
    large_man-made_outdoor_things: [0.4848, 0.5094, 0.5116]
    large_natural_outdoor_scenes: [0.4684, 0.4971, 0.5026]
    large_omnivores_and_herbivores: [0.4832, 0.4650, 0.3997]
    medium_mammals: [0.4511, 0.4291, 0.3669]
    non-insect_invertebrates: [0.5093, 0.4760, 0.4164]
    people: [0.5193, 0.4570, 0.4242]
    reptiles: [0.4877, 0.4781, 0.4336]
    small_mammals: [0.5117, 0.4798, 0.4125]
    trees: [0.4544, 0.4833, 0.4314]
    vehicles_1: [0.4979, 0.4858, 0.4642]
    vehicles_2: [0.5301, 0.5280, 0.5037]
  std:
    cifar100: [0.2673, 0.2564, 0.2762]
    two_class: [0.26, 0.2517, 0.268]
    aquatic_mammals: [0.2495, 0.2327, 0.2515]
    fish: [0.2857, 0.2574, 0.2705]
    flowers: [0.2892, 0.2489, 0.2613]
    food_containers: [0.2761, 0.2782, 0.2888]
    fruit_and_vegetables: [0.2902, 0.2837, 0.2952]
    household_electrical_devices: [0.2933, 0.2937, 0.3028]
    household_furniture: [0.2603, 0.2774, 0.2956]
    insects: [0.2736, 0.2630, 0.2923]
    large_carnivores: [0.2352, 0.2244, 0.2276]
    large_man-made_outdoor_things: [0.2408, 0.2411, 0.2736]
    large_natural_outdoor_scenes: [0.2349, 0.2283, 0.2731]
    large_omnivores_and_herbivores: [0.2428, 0.2375, 0.2373]
    medium_mammals: [0.2355, 0.2248, 0.2261]
    non-insect_invertebrates: [0.2645, 0.2566, 0.2684]
    people: [0.2801, 0.2735, 0.2794]
    reptiles: [0.2619, 0.2418, 0.2526]
    small_mammals: [0.2389, 0.2288, 0.2377]
    trees: [0.2356, 0.2345, 0.2817]
    vehicles_1: [0.2633, 0.2609, 0.2733]
    vehicles_2: [0.2730, 0.2693, 0.2874]
  DATASETS:
    - None                
    - aquatic_mammals
    - fish
    - flowers
    - food_containers
    - fruit_and_vegetables
    - household_electrical_devices
    - household_furniture
    - insects
    - large_carnivores
    - large_man-made_outdoor_things
    - large_natural_outdoor_scenes
    - large_omnivores_and_herbivores
    - medium_mammals
    - non-insect_invertebrates
    - people
    - reptiles
    - small_mammals
    - trees
    - vehicles_1
    - vehicles_2

n24news:
  train_path: /data_library/n24news/image/train
  test_path: /data_library/n24news/image/test
  subfolder: true
  num_classes: 6
  resize: [224, 224] # if arch='lenet', [32,32]
  random_horizontal_flip: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  DATASETS:
    - None
    - group1 # "Opinion", "Art_Design", "Television"
    - group2 # "Music", "Travel", "Real_Estate"
    - group3 # "Books", "Theater", "Health"
    - group4 # "Sports", "Science", "Food"
    - group5 # "Fashion_Style", "Movies", "Technology"
    - group6 # "Dance", "Media", "Style"

mscoco:
  train_path: /data_library/mscoco/image/train
  test_path: /data_library/mscoco/image/val
  subfolder: true
  num_classes: 15
  resize: [224, 224]
  random_horizontal_flip: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  DATASETS: 
    - None
    - Accessory
    - Animal1
    - Animal2
    - Appliance
    - Electronic
    - Food1
    - Food2
    - Furniture
    - Indoor
    - Kitchen
    - Outdoor
    - Sports1
    - Sports2
    - Vehicle1
    - Vehicle2


cub:
  train_path: /data/youlee/data_library/cub_200_2011/image/train
  test_path: /data/youlee/data_library/cub_200_2011/image/test
  subfolder: true
  num_classes: 27
  resize: [224, 224]
  random_horizontal_flip: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  DATASETS:
    - None
    - group1 # '001.Black_footed_Albatross', '002.Laysan_Albatross', '004.Groove_billed_Ani', '009.Brewer_Blackbird', '010.Red_winged_Blackbird'
    - group2 # '011.Rusty_Blackbird', '013.Bobolink', '014.Indigo_Bunting', '021.Eastern_Towhee', '026.Bronzed_Cowbird'
    - group3 # '027.Shiny_Cowbird', '029.American_Crow', '030.Fish_Crow', '031.Black_billed_Cuckoo', '035.Purple_Finch'
    - group4 # '036.Northern_Flicker', '038.Great_Crested_Flycatcher', '040.Olive_sided_Flycatcher', '041.Scissor_tailed_Flycatcher', '042.Vermilion_Flycatcher'
    - group5 # '044.Frigatebird', '045.Northern_Fulmar', '046.Gadwall', '047.American_Goldfinch', '048.European_Goldfinch'
    - group6 # '049.Boat_tailed_Grackle', '050.Eared_Grebe', '051.Horned_Grebe', '052.Pied_billed_Grebe', '053.Western_Grebe'
    - group7 # '054.Blue_Grosbeak', '055.Evening_Grosbeak', '056.Pine_Grosbeak', '057.Rose_breasted_Grosbeak', '059.California_Gull'
    - group8 # '061.Heermann_Gull', '062.Herring_Gull', '064.Ring_billed_Gull', '067.Anna_Hummingbird', '068.Ruby_throated_Hummingbird'
    - group9 # '069.Rufous_Hummingbird', '070.Green_Violetear', '071.Long_tailed_Jaeger', '072.Pomarine_Jaeger', '073.Blue_Jay'
    - group10 # '074.Florida_Jay', '076.Dark_eyed_Junco', '077.Tropical_Kingbird', '079.Belted_Kingfisher', '080.Green_Kingfisher'
    - group11 # '081.Pied_Kingfisher', '082.Ringed_Kingfisher', '083.White_breasted_Kingfisher', '085.Horned_Lark', '086.Pacific_Loon'
    - group12 # '088.Western_Meadowlark', '089.Hooded_Merganser', '090.Red_breasted_Merganser', '091.Mockingbird', '092.Nighthawk'
    - group13 # '094.White_breasted_Nuthatch', '095.Baltimore_Oriole', '096.Hooded_Oriole', '098.Scott_Oriole', '099.Ovenbird'
    - group14 # '100.Brown_Pelican', '102.Western_Wood_Pewee', '103.Sayornis', '104.American_Pipit', '106.Horned_Puffin'
    - group15 # '109.American_Redstart', '110.Geococcyx', '111.Loggerhead_Shrike', '112.Great_Grey_Shrike', '114.Black_throated_Sparrow'
    - group16 # '116.Chipping_Sparrow', '118.House_Sparrow', '120.Fox_Sparrow', '121.Grasshopper_Sparrow', '122.Harris_Sparrow'
    - group17 # '123.Henslow_Sparrow', '127.Savannah_Sparrow', '128.Seaside_Sparrow', '129.Song_Sparrow', '130.Tree_Sparrow'
    - group18 # '131.Vesper_Sparrow', '132.White_crowned_Sparrow', '133.White_throated_Sparrow', '134.Cape_Glossy_Starling', '136.Barn_Swallow'
    - group19 # '137.Cliff_Swallow', '138.Tree_Swallow', '139.Scarlet_Tanager', '140.Summer_Tanager', '142.Black_Tern'
    - group20 # '143.Caspian_Tern', '144.Common_Tern', '145.Elegant_Tern', '146.Forsters_Tern', '147.Least_Tern'
    - group21 # '148.Green_tailed_Towhee', '150.Sage_Thrasher', '152.Blue_headed_Vireo', '154.Red_eyed_Vireo', '155.Warbling_Vireo'
    - group22 # '156.White_eyed_Vireo', '158.Bay_breasted_Warbler', '159.Black_and_white_Warbler', '161.Blue_winged_Warbler', '162.Canada_Warbler'
    - group23 # '163.Cape_May_Warbler', '164.Cerulean_Warbler', '165.Chestnut_sided_Warbler', '167.Hooded_Warbler', '170.Mourning_Warbler'
    - group24 # '171.Myrtle_Warbler', '172.Nashville_Warbler', '173.Orange_crowned_Warbler', '174.Palm_Warbler', '175.Pine_Warbler'
    - group25 # '176.Prairie_Warbler', '177.Prothonotary_Warbler', '180.Wilson_Warbler', '182.Yellow_Warbler', '183.Northern_Waterthrush'
    - group26 # '184.Louisiana_Waterthrush', '185.Bohemian_Waxwing', '186.Cedar_Waxwing', '188.Pileated_Woodpecker', '189.Red_bellied_Woodpecker'
    - group27 # '191.Red_headed_Woodpecker', '192.Downy_Woodpecker', '193.Bewick_Wren', '194.Cactus_Wren', '195.Carolina_Wren'

oxford: 
  train_path: /data_library/oxford_102_flowers/image/train
  test_path: /data_library/oxford_102_flowers/image/test
  subfolder: true
  num_classes: 6
  resize: [64, 64]
  random_horizontal_flip: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  DATASETS:
    - None
    - group1 # "class_00051", "class_00072", "class_00082", "class_00060"
    - group2 # "class_00077", "class_00065", "class_00058", "class_00056"
    - group3 # "class_00046", "class_00074", "class_00037", "class_00080"
    - group4 # "class_00073", "class_00041", "class_00083", "class_00095"
    - group5 # "class_00089", "class_00081", "class_00075", "class_00076"
    - group6 # "class_00094", "class_00088", "class_00078", "class_00043"
    - group7
    - group8
    - group9
    - group10
    - group11
    - group12
  
  modality: 
    default: image
    text_groups: [group7, group8, group9, group10, group11, group12]
  text_train_path: /data_library/oxford_102_flowers/text/train
  text_test_path: /data_library/oxford_102_flowers/text/test