cifar100:
  train_path: /data_library/cifar100/train
  test_path: /data_library/cifar100/test
  subfolder: true 
  num_classes: 21
  crop:
    size: [32, 32]
    padding: 4
  random_horizontal_flip: true
  mean:
    cifar100: [0.5071, 0.4865, 0.4409]
    two_class: [0.5071, 0.4866, 0.4409]
    aquatic_mammals: [0.4242, 0.4783, 0.4975]
    fish: [0.4162, 0.4626, 0.4577]
    flowers: [0.5233, 0.4080, 0.3058]
    food_containers: [0.5824, 0.5459, 0.5111]
    fruit_and_vegetables: [0.6010, 0.4927, 0.3616]
    household_electrical_devices: [0.5573, 0.5368, 0.5251]
    household_furniture: [0.6104, 0.5407, 0.4902]
    insects: [0.5568, 0.5380, 0.4312]
    large_carnivores: [0.4719, 0.4395, 0.3713]
    large_man-made_outdoor_things: [0.4848, 0.5094, 0.5116]
    large_natural_outdoor_scenes: [0.4684, 0.4971, 0.5026]
    large_omnivores_and_herbivores: [0.4832, 0.4650, 0.3997]
    medium_mammals: [0.4511, 0.4291, 0.3669]
    non-insect_invertebrates: [0.5093, 0.4760, 0.4164]
    people: [0.5193, 0.4570, 0.4242]
    reptiles: [0.4877, 0.4781, 0.4336]
    small_mammals: [0.5117, 0.4798, 0.4125]
    trees: [0.4544, 0.4833, 0.4314]
    vehicles_1: [0.4979, 0.4858, 0.4642]
    vehicles_2: [0.5301, 0.5280, 0.5037]
  std:
    cifar100: [0.2673, 0.2564, 0.2762]
    two_class: [0.26, 0.2517, 0.268]
    aquatic_mammals: [0.2495, 0.2327, 0.2515]
    fish: [0.2857, 0.2574, 0.2705]
    flowers: [0.2892, 0.2489, 0.2613]
    food_containers: [0.2761, 0.2782, 0.2888]
    fruit_and_vegetables: [0.2902, 0.2837, 0.2952]
    household_electrical_devices: [0.2933, 0.2937, 0.3028]
    household_furniture: [0.2603, 0.2774, 0.2956]
    insects: [0.2736, 0.2630, 0.2923]
    large_carnivores: [0.2352, 0.2244, 0.2276]
    large_man-made_outdoor_things: [0.2408, 0.2411, 0.2736]
    large_natural_outdoor_scenes: [0.2349, 0.2283, 0.2731]
    large_omnivores_and_herbivores: [0.2428, 0.2375, 0.2373]
    medium_mammals: [0.2355, 0.2248, 0.2261]
    non-insect_invertebrates: [0.2645, 0.2566, 0.2684]
    people: [0.2801, 0.2735, 0.2794]
    reptiles: [0.2619, 0.2418, 0.2526]
    small_mammals: [0.2389, 0.2288, 0.2377]
    trees: [0.2356, 0.2345, 0.2817]
    vehicles_1: [0.2633, 0.2609, 0.2733]
    vehicles_2: [0.2730, 0.2693, 0.2874]
  DATASETS:
    - None                
    - aquatic_mammals
    - fish
    - flowers
    - food_containers
    - fruit_and_vegetables
    - household_electrical_devices
    - household_furniture
    - insects
    - large_carnivores
    - large_man-made_outdoor_things
    - large_natural_outdoor_scenes
    - large_omnivores_and_herbivores
    - medium_mammals
    - non-insect_invertebrates
    - people
    - reptiles
    - small_mammals
    - trees
    - vehicles_1
    - vehicles_2

n24news:
  train_path: /data_library/n24news/image/train
  test_path: /data_library/n24news/image/test
  subfolder: false
  num_classes: 24
  resize: [224, 224] # if arch='lenet', [32,32]
  crop:
    size: [16, 16]
  random_horizontal_flip: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  DATASETS:
    - None
    - group1 # "Opinion", "Art_Design", "Television"
    - group2 # "Music", "Travel", "Real_Estate"
    - group3 # "Books", "Theater", "Health"
    - group4 # "Sports", "Science", "Food"
    - group5 # "Fashion_Style", "Movies", "Technology"
    - group6 # "Dance", "Media", "Style"

mscoco:
  train_path: /data_library/mscoco/train_processed/image
  test_path: /data_library/mscoco/val_processed/image
  subfolder: false
  num_classes: 78
  resize: [224, 224]
  random_horizontal_flip: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  DATASETS:
    - airplane
    - apple
    - backpack
    - banana
    - baseball bat
    - baseball glove
    - bear
    - bed
    - bench
    - bicycle
    - bird
    - boat
    - book
    - bottle
    - bowl
    - broccoli
    - bus
    - cake
    - car
    - carrot
    - cat
    - cell phone
    - chair
    - clock
    - couch
    - cow
    - cup
    - dining table
    - dog
    - donut
    - elephant
    - fire hydrant
    - fork
    - frisbee
    - giraffe
    - hair drier
    - handbag
    - horse
    - hot dog
    - keyboard
    - kite
    - knife
    - laptop
    - microwave
    - motorcycle
    - mouse
    - orange
    - oven
    - parking meter
    - person
    - pizza
    - potted plant
    - refrigerator
    - remote
    - sandwich
    - scissors
    - sheep
    - sink
    - skateboard
    - skis
    - snowboard
    - spoon
    - sports ball
    - stop sign
    - suitcase
    - surfboard
    - teddy bear
    - tennis racket
    - tie
    - toaster
    - toilet
    - toothbrush
    - traffic light
    - train
    - truck
    - tv
    - umbrella
    - vase
    - wine glass
    - zebra


cub:
  train_path: 
  test_path: 
  subfolder: false
  num_classes: 200
  resize: [224, 224]
  random_horizontal_flip: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  DATASETS:
    - 001.Black_footed_Albatross
    - 002.Laysan_Albatross
    - 003.Sooty_Albatross
    - 004.Groove_billed_Ani
    - 005.Crested_Auklet
    - 006.Least_Auklet
    - 007.Parakeet_Auklet
    - 008.Rhinoceros_Auklet
    - 009.Brewer_Blackbird
    - 010.Red_winged_Blackbird
    - 011.Rusty_Blackbird
    - 012.Yellow_headed_Blackbird
    - 013.Bobolink
    - 014.Indigo_Bunting
    - 015.Lazuli_Bunting
    - 016.Painted_Bunting
    - 017.Cardinal
    - 018.Spotted_Catbird
    - 019.Gray_Catbird
    - 020.Yellow_breasted_Chat
    - 021.Eastern_Towhee
    - 022.Chuck_will_Widow
    - 023.Brandt_Cormorant
    - 024.Red_faced_Cormorant
    - 025.Pelagic_Cormorant
    - 026.Bronzed_Cowbird
    - 027.Shiny_Cowbird
    - 028.Brown_Creeper
    - 029.American_Crow
    - 030.Fish_Crow
    - 031.Black_billed_Cuckoo
    - 032.Mangrove_Cuckoo
    - 033.Yellow_billed_Cuckoo
    - 034.Gray_crowned_Rosy_Finch
    - 035.Purple_Finch
    - 036.Northern_Flicker
    - 037.Acadian_Flycatcher
    - 038.Great_Crested_Flycatcher
    - 039.Least_Flycatcher
    - 040.Olive_sided_Flycatcher
    - 041.Scissor_tailed_Flycatcher
    - 042.Vermilion_Flycatcher
    - 043.Yellow_bellied_Flycatcher
    - 044.Frigatebird
    - 045.Northern_Fulmar
    - 046.Gadwall
    - 047.American_Goldfinch
    - 048.European_Goldfinch
    - 049.Boat_tailed_Grackle
    - 050.Eared_Grebe
    - 051.Horned_Grebe
    - 052.Pied_billed_Grebe
    - 053.Western_Grebe
    - 054.Blue_Grosbeak
    - 055.Evening_Grosbeak
    - 056.Pine_Grosbeak
    - 057.Rose_breasted_Grosbeak
    - 058.Pigeon_Guillemot
    - 059.California_Gull
    - 060.Glaucous_winged_Gull
    - 061.Heermann_Gull
    - 062.Herring_Gull
    - 063.Ivory_Gull
    - 064.Ring_billed_Gull
    - 065.Slaty_backed_Gull
    - 066.Western_Gull
    - 067.Anna_Hummingbird
    - 068.Ruby_throated_Hummingbird
    - 069.Rufous_Hummingbird
    - 070.Green_Violetear
    - 071.Long_tailed_Jaeger
    - 072.Pomarine_Jaeger
    - 073.Blue_Jay
    - 074.Florida_Jay
    - 075.Green_Jay
    - 076.Dark_eyed_Junco
    - 077.Tropical_Kingbird
    - 078.Gray_Kingbird
    - 079.Belted_Kingfisher
    - 080.Green_Kingfisher
    - 081.Pied_Kingfisher
    - 082.Ringed_Kingfisher
    - 083.White_breasted_Kingfisher
    - 084.Red_legged_Kittiwake
    - 085.Horned_Lark
    - 086.Pacific_Loon
    - 087.Common_Loon
    - 088.White_necked_Raven
    - 089.Philadelphia_Vireo
    - 090.Warbling_Vireo
    - 091.White_eyed_Vireo
    - 092.Yellow_throated_Vireo
    - 093.Bay_breasted_Warbler
    - 094.Black_and_white_Warbler
    - 095.Black_throated_Blue_Warbler
    - 096.Blue_winged_Warbler
    - 097.Canada_Warbler
    - 098.Cape_May_Warbler
    - 099.Cerulean_Warbler
    - 100.Chestnut_sided_Warbler
    - 101.Golden_winged_Warbler
    - 102.Hooded_Warbler
    - 103.Kentucky_Warbler
    - 104.Magnolia_Warbler
    - 105.Mourning_Warbler
    - 106.Myrtle_Warbler
    - 107.Nashville_Warbler
    - 108.Orange_crowned_Warbler
    - 109.Palm_Warbler
    - 110.Pine_Warbler
    - 111.Prairie_Warbler
    - 112.Prothonotary_Warbler
    - 113.Swainson_Warbler
    - 114.Tennessee_Warbler
    - 115.Wilson_Warbler
    - 116.Worm_eating_Warbler
    - 117.Yellow_Warbler
    - 118.Northern_Waterthrush
    - 119.Louisiana_Waterthrush
    - 120.Bohemian_Waxwing
    - 121.Cedar_Waxwing
    - 122.American_Three_toed_Woodpecker
    - 123.Pileated_Woodpecker
    - 124.Red_bellied_Woodpecker
    - 125.Red_cockaded_Woodpecker
    - 126.Red_headed_Woodpecker
    - 127.Downy_Woodpecker
    - 128.Bewick_Wren
    - 129.Cactus_Wren
    - 130.Carolina_Wren
    - 131.House_Wren
    - 132.Marsh_Wren
    - 133.Rock_Wren
    - 134.Winter_Wren
    - 135.Common_Yellowthroat
    - 136.Wilson_Snipe
    - 137.American_White_Pelican
    - 138.Brown_Pelican
    - 139.White_Pelican
    - 140.Scarlet_Tanager
    - 141.Summer_Tanager
    - 142.Western_Tanager
    - 143.Northern_Shrike
    - 144.Loggerhead_Shrike
    - 145.Baltimore_Oriole
    - 146.Orchard_Oriole
    - 147.Hooded_Oriole
    - 148.Bullock_Oriole
    - 149.House_Finch
    - 150.Purple_Martin
    - 151.Tree_Swallow
    - 152.Barn_Swallow
    - 153.Whip_poor_Will
    - 154.Yellow_billed_Loon
    - 155.Common_Murre
    - 156.Thick_billed_Murre
    - 157.Bobwhite
    - 158.Ring_necked_Pheasant
    - 159.Ruffed_Grouse
    - 160.Sage_Grouse
    - 161.Sharp_tailed_Grouse
    - 162.Wild_Turkey
    - 163.Bald_Eagle
    - 164.Golden_Eagle
    - 165.Marsh_Hawk
    - 166.Cooper_Hawk
    - 167.Red_tailed_Hawk
    - 168.Rough_legged_Hawk
    - 169.Ferruginous_Hawk
    - 170.American_Kestrel
    - 171.Merlin
    - 172.Peregrine_Falcon
    - 173.Prairie_Falcon
    - 174.Great_Horned_Owl
    - 175.Snowy_Owl
    - 176.Barred_Owl
    - 177.Great_Grey_Owl
    - 178.Northern_Hawk_Owl
    - 179.Long_eared_Owl
    - 180.Short_eared_Owl
    - 181.Boreal_Owl
    - 182.Northern_Saw_whet_Owl
    - 183.Belted_Kingfisher
    - 184.Roadrunner
    - 185.Common_Poorwill
    - 186.Chimney_Swift
    - 187.Ruby_throated_Hummingbird
    - 188.Rufous_Hummingbird
    - 189.Green_Violetear
    - 190.Western_Scrub_Jay
    - 191.American_Magpie
    - 192.Clark_Nutcracker
    - 193.House_Sparrow
    - 194.Evening_Grosbeak
    - 195.Black_capped_Chickadee
    - 196.Mountain_Chickadee
    - 197.Tufted_Titmouse
    - 198.White_breasted_Nuthatch
    - 199.Red_breasted_Nuthatch
    - 200.Brown_Creeper


oxford: 
  train_path: 
  test_path:
  subfolder: false
  num_classes: 102
  resize: [224, 224]
  random_horizontal_flip: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  DATASETS:
    - class_00001
    - class_00002
    - class_00003
    - class_00004
    - class_00005
    - class_00006
    - class_00007
    - class_00008
    - class_00009
    - class_00010
    - class_00011
    - class_00012
    - class_00013
    - class_00014
    - class_00015
    - class_00016
    - class_00017
    - class_00018
    - class_00019
    - class_00020
    - class_00021
    - class_00022
    - class_00023
    - class_00024
    - class_00025
    - class_00026
    - class_00027
    - class_00028
    - class_00029
    - class_00030
    - class_00031
    - class_00032
    - class_00033
    - class_00034
    - class_00035
    - class_00036
    - class_00037
    - class_00038
    - class_00039
    - class_00040
    - class_00041
    - class_00042
    - class_00043
    - class_00044
    - class_00045
    - class_00046
    - class_00047
    - class_00048
    - class_00049
    - class_00050
    - class_00051
    - class_00052
    - class_00053
    - class_00054
    - class_00055
    - class_00056
    - class_00057
    - class_00058
    - class_00059
    - class_00060
    - class_00061
    - class_00062
    - class_00063
    - class_00064
    - class_00065
    - class_00066
    - class_00067
    - class_00068
    - class_00069
    - class_00070
    - class_00071
    - class_00072
    - class_00073
    - class_00074
    - class_00075
    - class_00076
    - class_00077
    - class_00078
    - class_00079
    - class_00080
    - class_00081
    - class_00082
    - class_00083
    - class_00084
    - class_00085
    - class_00086
    - class_00087
    - class_00088
    - class_00089
    - class_00090
    - class_00091
    - class_00092
    - class_00093
    - class_00094
    - class_00095
    - class_00096
    - class_00097
    - class_00098
    - class_00099
    - class_00100
    - class_00101
    - class_00102