mscoco:
  train_image_path: "/data_library/mscoco/train_processed/image"
  train_caption_path: "/data_library/mscoco/train_processed/caption"
  test_image_path: "/data_library/mscoco/val_processed/image"   
  test_caption_path: "/data_library/mscoco/val_processed/caption"
  subfolder: false
  num_classes: 78
  resize: [224, 224]
  random_horizontal_flip: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  DATASETS:
    - airplane
    - apple
    - backpack
    - banana
    - baseball bat
    - baseball glove
    - bear
    - bed
    - bench
    - bicycle
    - bird
    - boat
    - book
    - bottle
    - bowl
    - broccoli
    - bus
    - cake
    - car
    - carrot
    - cat
    - cell phone
    - chair
    - clock
    - couch
    - cow
    - cup
    - dining table
    - dog
    - donut
    - elephant
    - fire hydrant
    - fork
    - frisbee
    - giraffe
    - hair drier
    - handbag
    - horse
    - hot dog
    - keyboard
    - kite
    - knife
    - laptop
    - microwave
    - motorcycle
    - mouse
    - orange
    - oven
    - parking meter
    - person
    - pizza
    - potted plant
    - refrigerator
    - remote
    - sandwich
    - scissors
    - sheep
    - sink
    - skateboard
    - skis
    - snowboard
    - spoon
    - sports ball
    - stop sign
    - suitcase
    - surfboard
    - teddy bear
    - tennis racket
    - tie
    - toaster
    - toilet
    - toothbrush
    - traffic light
    - train
    - truck
    - tv
    - umbrella
    - vase
    - wine glass
    - zebra